<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" ignored="0" total="1" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="46479" started-at="2017-08-10T04:39:54Z" finished-at="2017-08-10T04:40:40Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="46479" started-at="2017-08-10T04:39:54Z" finished-at="2017-08-10T04:40:40Z">
      <class name="com.test.automation.UIAutomation.homepage.TC001_VerifyLoginWithInvalidCredentials">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.test.automation.UIAutomation.homepage.TC001_VerifyLoginWithInvalidCredentials@12cdcf4]" name="setUp" is-config="true" duration-ms="33680" started-at="2017-08-10T10:09:54Z" finished-at="2017-08-10T10:10:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:com.test.automation.UIAutomation.homepage.TC001_VerifyLoginWithInvalidCredentials@12cdcf4]" name="beforeMethod" is-config="true" duration-ms="8" started-at="2017-08-10T10:10:28Z" finished-at="2017-08-10T10:10:28Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.test.automation.UIAutomation.homepage.TC001_VerifyLoginWithInvalidCredentials.verifyLoginWithInvalidCredentials() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="verifyLoginWithInvalidCredentials()[pri:0, instance:com.test.automation.UIAutomation.homepage.TC001_VerifyLoginWithInvalidCredentials@12cdcf4]" name="verifyLoginWithInvalidCredentials" duration-ms="10280" started-at="2017-08-10T10:10:28Z" finished-at="2017-08-10T10:10:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginWithInvalidCredentials -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.test.automation.UIAutomation.homepage.TC001_VerifyLoginWithInvalidCredentials@12cdcf4]" name="afterMethod" is-config="true" duration-ms="1" started-at="2017-08-10T10:10:38Z" finished-at="2017-08-10T10:10:38Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyLoginWithInvalidCredentials status=SUCCESS method=TC001_VerifyLoginWithInvalidCredentials.verifyLoginWithInvalidCredentials()[pri:0, instance:com.test.automation.UIAutomation.homepage.TC001_VerifyLoginWithInvalidCredentials@12cdcf4] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="endTest()[pri:0, instance:com.test.automation.UIAutomation.homepage.TC001_VerifyLoginWithInvalidCredentials@12cdcf4]" name="endTest" is-config="true" duration-ms="2432" started-at="2017-08-10T10:10:38Z" finished-at="2017-08-10T10:10:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endTest -->
      </class> <!-- com.test.automation.UIAutomation.homepage.TC001_VerifyLoginWithInvalidCredentials -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
